---
sidebar: sidebar 
permalink: data-analytics/dremio-lakehouse-solution.html 
keywords: solution, architecture, details, hardware, software 
summary: Dieser Abschnitt behandelt die für die Dremio-Zertifizierung verwendete Hardware und Software.  Diese Informationen gelten für die Dremio-Bereitstellung mit NetApp Speicher. 
---
= Lösungsübersicht
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Die Hybrid Iceberg Lakehouse-Lösung bietet einzigartige Vorteile zur Bewältigung der Herausforderungen, mit denen Data Lake-Kunden konfrontiert sind.  Durch die Nutzung der Dremio Unified Lakehouse-Plattform und der NetApp ONTAP, StorageGRID und NetApp Cloud-Lösungen können Unternehmen ihren Geschäftsbetrieb erheblich aufwerten.  Die Lösung bietet nicht nur Zugriff auf mehrere Datenquellen, einschließlich NetApp Quellen, sondern verbessert auch die allgemeine Analyseleistung und hilft Unternehmen dabei, Geschäftseinblicke zu gewinnen, die zu Geschäftswachstum führen.



== NetApp Übersicht

* Die Angebote von NetApp, wie ONTAP und StorageGRID, ermöglichen die Trennung von Speicher und Computing und ermöglichen so eine optimale Ressourcennutzung basierend auf spezifischen Anforderungen.  Diese Flexibilität ermöglicht es Kunden, ihren Speicher mithilfe von NetApp -Speicherlösungen unabhängig zu skalieren
* Durch die Nutzung der Speichercontroller von NetApp können Kunden mithilfe der Protokolle NFS und S3 effizient Daten an ihre Vektordatenbank übermitteln.  Diese Protokolle erleichtern die Speicherung von Kundendaten und verwalten den Vektordatenbankindex, sodass nicht mehr mehrere Kopien der Daten benötigt werden, auf die über Datei- und Objektmethoden zugegriffen wird.
* NetApp ONTAP bietet native Unterstützung für NAS- und Objektspeicher bei führenden Cloud-Service-Anbietern wie AWS, Azure und Google Cloud.  Diese umfassende Kompatibilität gewährleistet eine nahtlose Integration und ermöglicht Kundendatenmobilität, globale Zugänglichkeit, Notfallwiederherstellung, dynamische Skalierbarkeit und hohe Leistung.




=== StorageGRID

Unser branchenführender Objektspeicher storageGRID bietet eine leistungsstarke Richtlinien-Engine für die automatisierte Datenplatzierung, flexible Bereitstellungsoptionen und unübertroffene Haltbarkeit mit mehrschichtiger Löschcodierung.  Es verfügt über eine skalierbare Architektur, die Milliarden von Objekten und Petabyte an Daten in einem einzigen Namespace unterstützt.  Die Lösung ermöglicht die Integration einer Hybrid-Cloud und ermöglicht so die Datenaufteilung auf die wichtigsten Cloud-Plattformen.  Es wurde im IDC Marketscape Worldwide Object-Based Vendor Assessment 2019 als führend anerkannt.

Darüber hinaus zeichnet sich storageGRID durch die Verwaltung unstrukturierter Daten im großen Maßstab mit softwaredefiniertem Objektspeicher, Georedundanz und Multi-Site-Funktionen aus.  Es umfasst ein richtlinienbasiertes Informationslebenszyklusmanagement und bietet Cloud-Integrationsfunktionen wie Spiegelung und Suche.  Es verfügt über verschiedene Zertifizierungen, darunter Common Criteria, NF203 Digital Safe Component, ISO/IEC 25051, KPMG und Cohasset Compliance Assessment.

Zusammenfassend bietet NetApp storageGRID leistungsstarke Funktionen, Skalierbarkeit, Hybrid-Cloud-Integration und Compliance-Zertifizierungen für die effiziente Verwaltung unstrukturierter Daten im großen Maßstab.



=== NetApp ONTAP

NetApp ONTAP ist eine robuste Speicherlösung, die eine breite Palette an Unternehmensfunktionen bietet.  Es enthält Snapshot, das anwendungskonsistente und manipulationssichere Sofortsicherungen bietet.  SnapRestore ermöglicht die nahezu sofortige Wiederherstellung von Backups auf Anfrage, während SnapMirror integrierte Remote-Backup- und Disaster-Recovery-Funktionen bietet.  Die Lösung umfasst außerdem Autonomous Ransomware Protection (ARP) und gewährleistet Datensicherheit mit Funktionen wie Multi-Administrator-Verifizierung, Data-at-Rest-Verschlüsselung mit FIPS-Zertifizierung, Datenverschlüsselung während der Übertragung, Multifaktor-Authentifizierung (MFA) und rollenbasierter Zugriffskontrolle (RBAC).  Umfassende Protokollierung, Auditierung, integrierte und externe Schlüsselverwaltung, sichere Bereinigung und sichere Verwaltung mehrerer Mandanten verbessern die Datensicherheit und Compliance zusätzlich.

NetApp ONTAP verfügt außerdem über SnapLock, das eine gesetzeskonforme Datenaufbewahrung mit einem hohen Maß an Integrität, Leistung und Aufbewahrung bei niedrigen Gesamtbetriebskosten bietet.  Es ist vollständig in NetApp ONTAP 9 integriert und bietet Schutz vor böswilligen Handlungen, betrügerischen Administratoren und Ransomware.

Die Lösung umfasst NSE/NVE-Verschlüsselung für die Verschlüsselung von In-Flight- und Data-at-Rest-Daten, Multifaktor-Administratorzugriff und Multi-Admin-Verifizierung.  Active IQ bietet KI-gestützte prädiktive Analysen und Korrekturmaßnahmen, während QoS die Kontrolle der Service-Workload-Qualität gewährleistet.  Die Verwaltungs- und Automatisierungsintegration erfolgt intuitiv über SysMgr/GUI/CLI/API.  FabricPool ermöglicht automatisches Daten-Tiering und die Lösung bietet Effizienz durch Inline-Datenkomprimierung, Deduplizierung und Kompaktierung.  NetApp garantiert die Erreichung der Workload-Effizienzziele ohne Kosten für den Kunden.

NetApp ONTAP unterstützt verschiedene Protokolle, darunter NVMe/FC, FC, NVMe/TCP, iSCSI, NFS, SMB und S3, und ist damit eine einheitliche Speicherlösung.  Insgesamt bietet NetApp ONTAP umfangreiche Unternehmensfunktionen, robuste Sicherheit, Compliance, Effizienz und Vielseitigkeit, um den unterschiedlichsten Speicheranforderungen gerecht zu werden.



== Dremio-Übersicht

Dremio ist die Unified Lakehouse-Plattform für Self-Service-Analysen und KI.  Die Dremio Unified Analytics Platform bringt Benutzer mit Lakehouse-Flexibilität, Skalierbarkeit und Leistung näher an die Daten heran – und das zu einem Bruchteil der Kosten herkömmlicher Data-Warehouse-Lösungen.  Dremio ermöglicht „Shift-Left“-Analysen, um komplexe und kostspielige Datenintegration und ETL zu eliminieren und nahtlose Analysen im Unternehmensmaßstab ohne Datenbewegung zu ermöglichen.  Dremio bietet außerdem:

* Benutzerfreundliche Self-Service-Analysen werden durch eine universelle semantische Ebene und eine eng integrierte, hochleistungsfähige SQL-Abfrage-Engine ermöglicht. Dadurch wird die Verbindung, Verwaltung und Analyse aller Daten sowohl in der Cloud als auch vor Ort vereinfacht.
* Die Apache Iceberg-nativen Lakehouse-Verwaltungsfunktionen von Dremio vereinfachen die Datenermittlung und automatisieren die Datenoptimierung, indem sie leistungsstarke Analysen mit Git-inspirierter Datenversionierung liefern.
* Dremio basiert auf Open Source und offenen Standards und ermöglicht es Unternehmen, Lock-in-Situationen zu vermeiden und für Innovationen gerüstet zu bleiben.  Großunternehmen vertrauen auf Dremio als die benutzerfreundlichste Lakehouse-Plattform mit dem besten Preis-Leistungs-Verhältnis für alle Workloads.




== Welchen Mehrwert bietet die Hybrid Iceberg Lakehouse-Lösung von Dremio und NetApp den Kunden?

* *Verbessertes Datenmanagement und -zugänglichkeit*: Dremio ist bekannt für seine Data-Lakehouse-Plattform, die es Unternehmen ermöglicht, Daten mit hoher Geschwindigkeit direkt aus ihren Data Lakes abzufragen.  NetApp hingegen ist ein führender Anbieter von Cloud-Datendiensten und Datenspeicherlösungen.  Das gemeinsame Angebot bietet Kunden eine umfassende Lösung für die effiziente und effiziente Speicherung, Verwaltung, den Zugriff und die Analyse ihrer Unternehmensdaten.
* *Leistungsoptimierung*: Mit der Expertise von NetApp im Bereich Datenspeicherung und den Fähigkeiten von Dremio in der Datenverarbeitung und Datenoptimierung bietet die Partnerschaft eine Lösung, die die Leistung von Datenoperationen verbessert, die Latenz reduziert und die Geschwindigkeit der Geschäftserkenntnisse erhöht.  Dremio hat sogar Leistungsvorteile für die interne IT-Analyseinfrastruktur von NetApp gebracht.
* *Skalierbarkeit*: Sowohl Dremio als auch NetApp bieten eine Lösung, die auf Skalierbarkeit ausgelegt ist.  Die gemeinsame Lösung bietet Kunden hochskalierbare Umgebungen für Datenspeicherung, Datenverwaltung und Analysen.  In einer hybriden Iceberg Lakehouse-Umgebung bietet die Dremio SQL-Abfrage-Engine in Kombination mit NetApp StorageGRID beispiellose Skalierbarkeit, Parallelität und Abfrageleistung und ist in der Lage, die Analyseanforderungen jedes Unternehmens zu erfüllen.
* *Datensicherheit und -verwaltung*: Beide Unternehmen legen großen Wert auf Datensicherheit und -verwaltung.  Zusammen bieten sie robuste Sicherheits- und Datenverwaltungsfunktionen und gewährleisten so den Schutz der Daten und die Einhaltung der Datenverwaltungsanforderungen.  Funktionen wie rollenbasierte und feinkörnige Zugriffskontrollen, umfassendes Auditing, durchgängige Datenherkunft, einheitliches Identitätsmanagement und SSO mit einem umfassenden Compliance- und Sicherheitsrahmen sorgen dafür, dass die analytischen Datenumgebungen von Unternehmen sicher und kontrolliert sind.
* *Kosteneffizienz*: Durch die Integration der Data Lake Engine von Dremio mit den Speicherlösungen von NetApp können Kunden die mit der Datenverwaltung und Datenbewegung verbundenen Kosten senken.  Unternehmen können außerdem von veralteten Data-Lake-Umgebungen auf eine modernere Lakehouse-Lösung aus NetApp und Dremio umsteigen.  Diese Hybrid Iceberg Lakehouse-Lösung bietet eine Hochgeschwindigkeitsabfrageleistung und marktführende Abfrageparallelität, die die Gesamtbetriebskosten senkt und die Zeit bis zur Erlangung geschäftlicher Erkenntnisse verkürzt.

