---
settings:
  name: NetApp artificial intelligence solutions
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    lipi_enabled: true
    harmony_enabled: false
  pdf:
    gen-type: named-only
    zip-level: 1
    zip-filename: netapp-solutions-ai.zip
  langs: de-de,us-en,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Lösungen für künstliche Intelligenz
    url: "/index.html"
  - title: Was ist neu
    url: "/whats-new.html"
  - section: ai-infrastructures
  - section: ai-data-pipelines
  - section: ai-use-cases
  - section: data-analytics
  - title: Videos
    url: "/videos/ai-ml-videos.html"
  - title: Blogs
    url: "/blogs.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: NetApp solutions
  repo: netapp-solutions-family
