---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'netapp, solutions, ai, what"s new, updates, change log' 
summary: Protokoll der jüngsten Änderungen am Material zu den NetApp -Lösungen für künstliche Intelligenz. 
---
= Neuigkeiten zu NetApp -Lösungen für künstliche Intelligenz
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Erfahren Sie, was es Neues bei Lösungen für künstliche Intelligenz gibt.



== 18. August 2025

Die NetApp Solutions-Site ist jetzt dielink:https://docs.netapp.com/us-en/netapp-solutions-family/index.html["NetApp Lösungsfamilie"^] , das die folgenden Websites umfasst:

* NetApp Lösungen für künstliche Intelligenz
* link:https://docs.netapp.com/us-en/netapp-solutions-containers/index.html["NetApp Container-Lösungen"^]
* link:https://docs.netapp.com/us-en/netapp-solutions-dataops/index.html["NetApp Datenmanagementlösungen"^]
* link:https://docs.netapp.com/us-en/netapp-solutions-databases/index.html["NetApp Datenbanklösungen"^]
* link:https://docs.netapp.com/us-en/netapp-solutions-cloud/index.html["NetApp Public- und Hybrid-Cloud-Lösungen"^]
* link:https://docs.netapp.com/us-en/netapp-solutions-sap/index.html["NetApp Lösungen für SAP"^]
* link:https://docs.netapp.com/us-en/netapp-solutions-virtualization/index.html["NetApp Virtualisierungslösungen"^]




== 3. Dezember 2025

Neue Lösung:link:software/ai-hybrid-union.html["Implementieren Sie hybrides KI-Training mit Union.ai und NetApp FlexCache."]

Nutzen Sie die Union.ai-Orchestrierung mit NetApp FlexCache , um KI-Trainingsworkloads auf Cloud-GPUs auszuführen und gleichzeitig sensible Daten lokal zu belassen.  FlexCache speichert nur die notwendigen Daten in der Cloud, um ein effizientes und sicheres hybrides Training zu gewährleisten.
