---
sidebar: sidebar 
permalink: software/ai-osmlops-trident-backend.html 
keywords: ONTAP, Trident, AI, Deployment, 
summary: Open Source MLOps mit NetApp – Beispiel Trident -Backends für NetApp AIPod Bereitstellungen 
---
= Beispiele für Trident -Backends für NetApp AIPod -Bereitstellungen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Bevor Sie Trident zur dynamischen Bereitstellung von Speicherressourcen in Ihrem Kubernetes-Cluster verwenden können, müssen Sie ein oder mehrere Trident -Backends erstellen.  Die folgenden Beispiele stellen verschiedene Arten von Backends dar, die Sie möglicherweise erstellen möchten, wenn Sie Komponenten dieser Lösung auf einemlink:../infra/ai-aipod-nv-intro.html["NetApp AIPod"^] .  Weitere Informationen zu Backends und beispielsweise Backends für andere Plattformen/Umgebungen finden Sie imlink:https://docs.netapp.com/us-en/trident/index.html["Trident -Dokumentation"^] .

. NetApp empfiehlt die Erstellung eines FlexGroup-fähigen Trident -Backends für Ihren AIPod.
+
Die folgenden Beispielbefehle zeigen die Erstellung eines FlexGroup-fähigen Trident -Backends für eine AIPod -Speicher-Virtual-Machine (SVM).  Dieses Backend verwendet die `ontap-nas-flexgroup` Speichertreiber.  ONTAP unterstützt zwei Hauptdatenvolumentypen: FlexVol und FlexGroup.  FlexVol -Volumes sind größenbeschränkt (zum Zeitpunkt der Erstellung dieses Dokuments hängt die maximale Größe von der jeweiligen Bereitstellung ab).  FlexGroup -Volumes hingegen können linear auf bis zu 20 PB und 400 Milliarden Dateien skaliert werden und bieten einen einzigen Namespace, der die Datenverwaltung erheblich vereinfacht.  Daher sind FlexGroup Volumes optimal für KI- und ML-Workloads, die auf großen Datenmengen basieren.

+
Wenn Sie mit einer kleinen Datenmenge arbeiten und FlexVol -Volumes anstelle von FlexGroup Volumes verwenden möchten, können Sie Trident -Backends erstellen, die die `ontap-nas` Speichertreiber anstelle des `ontap-nas-flexgroup` Speichertreiber.

+
....
$ cat << EOF > ./trident-backend-aipod-flexgroups-iface1.json
{
    "version": 1,
    "storageDriverName": "ontap-nas-flexgroup",
    "backendName": "aipod-flexgroups-iface1",
    "managementLIF": "10.61.218.100",
    "dataLIF": "192.168.11.11",
    "svm": "ontapai_nfs",
    "username": "admin",
    "password": "ontapai"
}
EOF
$ tridentctl create backend -f ./trident-backend-aipod-flexgroups-iface1.json -n trident
+-------------------------+---------------------+--------------------------------------+--------+---------+
|            NAME         |   STORAGE DRIVER    |                 UUID                 | STATE  | VOLUMES |
+-------------------------+---------------------+--------------------------------------+--------+---------+
| aipod-flexgroups-iface1 | ontap-nas-flexgroup | b74cbddb-e0b8-40b7-b263-b6da6dec0bdd | online |       0 |
+-------------------------+---------------------+--------------------------------------+--------+---------+
$ tridentctl get backend -n trident
+-------------------------+---------------------+--------------------------------------+--------+---------+
|            NAME         |   STORAGE DRIVER    |                 UUID                 | STATE  | VOLUMES |
+-------------------------+---------------------+--------------------------------------+--------+---------+
| aipod-flexgroups-iface1 | ontap-nas-flexgroup | b74cbddb-e0b8-40b7-b263-b6da6dec0bdd | online |       0 |
+-------------------------+---------------------+--------------------------------------+--------+---------+
....
. NetApp empfiehlt außerdem die Erstellung eines FlexVol-fähigen Trident Backends.  Möglicherweise möchten Sie FlexVol -Volumes zum Hosten persistenter Anwendungen, zum Speichern von Ergebnissen, Ausgaben, Debug-Informationen usw. verwenden.  Wenn Sie FlexVol Volumes verwenden möchten, müssen Sie ein oder mehrere FlexVol-fähige Trident Backends erstellen.  Die folgenden Beispielbefehle zeigen die Erstellung eines einzelnen FlexVol-fähigen Trident Backends.


....
$ cat << EOF > ./trident-backend-aipod-flexvols.json
{
    "version": 1,
    "storageDriverName": "ontap-nas",
    "backendName": "aipod-flexvols",
    "managementLIF": "10.61.218.100",
    "dataLIF": "192.168.11.11",
    "svm": "ontapai_nfs",
    "username": "admin",
    "password": "ontapai"
}
EOF
$ tridentctl create backend -f ./trident-backend-aipod-flexvols.json -n trident
+-------------------------+---------------------+--------------------------------------+--------+---------+
|            NAME         |   STORAGE DRIVER    |                 UUID                 | STATE  | VOLUMES |
+-------------------------+---------------------+--------------------------------------+--------+---------+
| aipod-flexvols          | ontap-nas           | 52bdb3b1-13a5-4513-a9c1-52a69657fabe | online |       0 |
+-------------------------+---------------------+--------------------------------------+--------+---------+
$ tridentctl get backend -n trident
+-------------------------+---------------------+--------------------------------------+--------+---------+
|            NAME         |   STORAGE DRIVER    |                 UUID                 | STATE  | VOLUMES |
+-------------------------+---------------------+--------------------------------------+--------+---------+
| aipod-flexvols          | ontap-nas           | 52bdb3b1-13a5-4513-a9c1-52a69657fabe | online |       0 |
| aipod-flexgroups-iface1 | ontap-nas-flexgroup | b74cbddb-e0b8-40b7-b263-b6da6dec0bdd | online |       0 |
+-------------------------+---------------------+--------------------------------------+--------+---------+
....