---
sidebar: sidebar 
permalink: software/ai-osmlops-trident-ops.html 
keywords: Trident 
summary: Open Source MLOps mit NetApp – Beispiel Trident Operations 
---
= Beispiel für Trident -Operationen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Dieser Abschnitt enthält Beispiele für verschiedene Vorgänge, die Sie möglicherweise mit Trident durchführen möchten.



== Importieren eines vorhandenen Volumes

Wenn auf Ihrem NetApp Speichersystem/Ihrer NetApp-Speicherplattform Volumes vorhanden sind, die Sie auf Containern innerhalb Ihres Kubernetes-Clusters mounten möchten, die aber nicht an PVCs im Cluster gebunden sind, müssen Sie diese Volumes importieren.  Sie können die Volume-Importfunktion von Trident verwenden, um diese Volumes zu importieren.

Die folgenden Beispielbefehle zeigen den Import eines Volumes mit dem Namen `pb_fg_all` .  Weitere Informationen zu PVCs finden Sie im https://kubernetes.io/docs/concepts/storage/persistent-volumes/["offizielle Kubernetes-Dokumentation"^] .  Weitere Informationen zur Funktion zum Importieren von Volumes finden Sie im https://docs.netapp.com/us-en/trident/index.html["Trident -Dokumentation"^] .

Ein `accessModes` Wert von `ReadOnlyMany` ist in den Beispiel-PVC-Spezifikationsdateien angegeben.  Weitere Informationen zum `accessMode` Feld finden Sie im https://kubernetes.io/docs/concepts/storage/persistent-volumes/["offizielle Kubernetes-Dokumentation"^] .

....
$ cat << EOF > ./pvc-import-pb_fg_all-iface1.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pb-fg-all-iface1
  namespace: default
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ontap-ai-flexgroups-retain-iface1
EOF
$ tridentctl import volume ontap-ai-flexgroups-iface1 pb_fg_all -f ./pvc-import-pb_fg_all-iface1.yaml -n trident
+--------------------------------+--------+-----------------------------------+----------+--------------------------------------------+--------+---------+
|          NAME                  |  SIZE  |       STORAGE CLASS               | PROTOCOL |             BACKEND UUID                         | STATE  | MANAGED |
+--------------------------------+--------+-----------------------------------+----------+------------------------------------------+--------+---------+
| default-pb-fg-all-iface1-7d9f1 | 10 TiB | ontap-ai-flexgroups-retain-iface1 | file     | b74cbddb-e0b8-40b7-b263-b6da6dec0bdd | online | true    |
+--------------------------------+--------+-----------------------------------+----------+--------------------------------------------+--------+---------+
$ tridentctl get volume -n trident
+----------------------------------+---------+-----------------------------------+----------+--------------------------------------+--------+---------+
|               NAME               |  SIZE   |           STORAGE CLASS           | PROTOCOL |             BACKEND UUID             | STATE  | MANAGED |
+----------------------------------+---------+-----------------------------------+----------+--------------------------------------+--------+---------+
| default-pb-fg-all-iface1-7d9f1   | 10 TiB  | ontap-ai-flexgroups-retain-iface1 | file     | b74cbddb-e0b8-40b7-b263-b6da6dec0bdd | online | true    |
+----------------------------------+---------+-----------------------------------+----------+--------------------------------------+--------+---------+
$ kubectl get pvc
NAME                 STATUS   VOLUME                             CAPACITY         ACCESS MODES   STORAGECLASS                        AGE
pb-fg-all-iface1     Bound    default-pb-fg-all-iface1-7d9f1     10995116277760   ROX            ontap-ai-flexgroups-retain-iface1   25h
....


== Bereitstellen eines neuen Volumes

Sie können Trident verwenden, um ein neues Volume auf Ihrem NetApp Speichersystem oder Ihrer NetApp-Plattform bereitzustellen.



=== Bereitstellen eines neuen Volumes mit kubectl

Die folgenden Beispielbefehle zeigen die Bereitstellung eines neuen FlexVol volume mit kubectl.

Ein `accessModes` Wert von `ReadWriteMany` ist in der folgenden Beispiel-PVC-Definitionsdatei angegeben.  Weitere Informationen zum `accessMode` Feld finden Sie im https://kubernetes.io/docs/concepts/storage/persistent-volumes/["offizielle Kubernetes-Dokumentation"^] .

....
$ cat << EOF > ./pvc-tensorflow-results.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tensorflow-results
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ontap-ai-flexvols-retain
EOF
$ kubectl create -f ./pvc-tensorflow-results.yaml
persistentvolumeclaim/tensorflow-results created
$ kubectl get pvc
NAME                              STATUS    VOLUME                             CAPACITY         ACCESS MODES   STORAGECLASS                        AGE
pb-fg-all-iface1                  Bound     default-pb-fg-all-iface1-7d9f1     10995116277760   ROX            ontap-ai-flexgroups-retain-iface1   26h
tensorflow-results                Bound     default-tensorflow-results-2fd60   1073741824       RWX            ontap-ai-flexvols-retain            25h
....


=== Bereitstellen eines neuen Volumes mit dem NetApp DataOps Toolkit

Sie können auch das NetApp DataOps Toolkit für Kubernetes verwenden, um ein neues Volume auf Ihrem NetApp -Speichersystem oder Ihrer NetApp-Plattform bereitzustellen.  Das NetApp DataOps Toolkit für Kubernetes nutzt Trident zur Bereitstellung von Volumes, vereinfacht den Prozess für den Benutzer jedoch. Weitere Informationen finden Sie imlink:https://github.com/NetApp/netapp-dataops-toolkit/blob/main/netapp_dataops_k8s/docs/volume_management.md["Dokumentation"] für Details.
